#
#
# ${project.name}
# v${project.version}
#
# 
## CONFIGURATION ##
#
# For information on the configuration, please see:
# https://github.com/A248/ArimBans/wiki/Configuration
#
#
storage:
  mode: 'file'
  file:
    url: 'jdbc:hsqldb:file:<file>'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'punishment'
    user: 'ArimBans'
    password: 'defaultpassword'
    url: 'jdbc:mysql://<ip>:<port>/<database>?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
  min-connections: 2
  max-connections: 5
formatting:
  use-json: true
  permanent-display: 'Permanently'
  console-display: 'Console'
  date: 'dd/MM/yyyy HH:mm:ss'
priorities:
  bans: 'HIGHEST'
  mutes: 'HIGHEST'
fetchers:
  internal: true
  ashcon: true
  mojang: true
other:
  version: '${project.version}'