#
#
# # ${project.name}
# # v${project.version}
#
# 
# ## CONFIGURATION ##
#
# For information on the configuration, please see:
# https://github.com/A248/ArimBans/wiki/Configuration
#
#
# ### Config.yml ###
#
storage:
  mode: 'file'
  table-prefix: 'arimbans_'
  file:
    url: 'jdbc:hsqldb:file:%FILE%;hsqldb.lock_file=false'
    filename: 'data'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'punishment'
    username: 'ArimBans'
    password: 'defaultpassword'
    url: 'jdbc:mysql://%HOST%:%PORT%/%DATABASE%?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
  min-connections: 2
  max-connections: 5
  restart-on-reload: false
formatting:
  use-json: true
  permanent-arguments:
    - 'perm'
    - 'permanent'
    - 'permanently'
  permanent-display: 'Permanently'
  console-display: 'Console'
  date: 'dd/MM/yyyy HH:mm:ss'
commands:
  op-permissions: true
  reasons:
    permit-blank: false
    default-reason: 'No reason stated.'
  block-for-muted:
    - 'me'
  confirm-unpunish:
    unbans: false
    unmutes: false
    unwarns: false
  rollback-detail: true
enforcement:
  strict-ip-checking: true
  priorities:
    bans: 'HIGHEST'
    mutes: 'HIGHEST'
fetchers:
  uuids:
    internal: true
    ashcon: true
    mojang: true
  geoip:
    ipstack:
      enabled: false
      key: 'nokey'
    freegeoip: true
    ipapi: true
config-version: 1