#
#
# # ${project.name}
# # v${project.version}
#
# 
# ## CONFIGURATION ##
#
# For information on the configuration, please see:
# https://github.com/A248/ArimBans/wiki/Configuration
#
#
# ### Config.yml ###
#
storage:
  mode: 'file'
  file:
    url: 'jdbc:hsqldb:file:<file>'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'punishment'
    user: 'ArimBans'
    password: 'defaultpassword'
    url: 'jdbc:mysql://<ip>:<port>/<database>?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
  min-connections: 2
  max-connections: 5
formatting:
  use-json: true
  permanent-arguments:
    - 'perm'
    - 'permanent'
    - 'permanently'
  permanent-display: 'Permanently'
  console-display: 'Console'
  date: 'dd/MM/yyyy HH:mm:ss'
commands:
  op-permissions: true
  detection:
    strict-mode: false
    ip-conversion: true
    time-detection: true
priorities:
  bans: 'HIGHEST'
  mutes: 'HIGHEST'
fetchers:
  uuids:
    internal: true
    ashcon: true
    mojang: true
  ips:
    ipstack:
      enabled: false
      key: 'nokey'
    freegeoip:
      enabled: true
other:
  config-version: 1
  plugin-version: '${project.version}'