name: ${project.name}
main: ${project.groupId}.${project.artifactId}.ArimBansBukkit
version: ${project.version}
author: A248
description: ArimBans is the ultimate punitive solution for single servers and networks, seeking to maximise efficiency through near-total asynchronous operation.

commands:
  arimbans:
    description: Everything related to ArimBans
    usage: /arimbans <arguments>