name: ${project.name}
main: ${project.groupId}.bans.ArimBansBukkit
version: ${project.version}
author: A248
description: ${project.description}
depend: [ArimAPI]
softdepend: [Vault]

commands:
  arimbans:
    description: Everything related to ArimBans
    usage: /arimbans <arguments>