name: ${project.name}
main: ${project.groupId}.${project.artifactId}.ArimBansBukkit
version: ${project.version}
author: A248
description: ${project.description}

commands:
  arimbans:
    description: Everything related to ArimBans
    usage: /arimbans <arguments>