name: ${plugin.name}
main: space.arim.bans.ArimBansBukkit
version: ${plugin.version}
author: ${plugin.author}
website: ${plugin.url}
description: ${plugin.description}
depend: [ArimAPI]
softdepend: [Vault]

commands:
  arimbans:
    description: Everything related to ArimBans
    usage: /arimbans <arguments>