name: ${project.name}
main: ${project.groupId}.${project.artifactId}.ArimBansBukkit
version: ${project.version}
author: Aerodactyl_
description: Fully re-coded java-based version of ArimBans2.sk

commands:
  arimbans:
    description: Everything related to ArimBans
    usage: /arimbans <arguments>