#
#
# # ${project.name}
# # v${project.version}
#
# 
# ## CONFIGURATION ##
#
# For information on the configuration, please see:
# https://github.com/A248/ArimBans/wiki/Configuration
#
#
# ### Config.yml ###
#
storage:
  mode: 'file'
  table-prefix: 'arimbans_'
  file:
    url: 'jdbc:hsqldb:file:%FILE%;hsqldb.lock_file=false;sql.syntax_mys=true'
    filename: 'data/database'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'punishment'
    username: 'ArimBans'
    password: 'defaultpassword'
    url: 'jdbc:mysql://%HOST%:%PORT%/%DATABASE%?autoReconnect=true&useUnicode=true&characterEncoding=utf8'
  restart-on-reload: false
formatting:
  use-json: true
  permanent-arguments:
    - 'perm'
    - 'permanent'
    - 'permanently'
  permanent-display: 'Permanently'
  console-display: 'Console'
  dates: 'dd/MM/yyyy HH:mm:ss'
commands:
  op-permissions: true
  reasons:
    permit-blank: false
    default-reason: 'No reason stated.'
  confirm-unpunish:
    unbans: false
    unmutes: false
    unwarns: false
  rollback-detail: true
  block-for-muted:
    - 'me'
    - 'say'
    - 'action'
    - 'eaction'
    - 'describe'
    - 'edescribe'
    - 'eme'
    - 'w'
    - 'm'
    - 'pm'
    - 'whisper'
    - 'ewhisper'
    - 'emsg'
    - 'msg'
    - 'message'
    - 'etell'
    - 'tell'
    - 'er'
    - 'r'
    - 'reply'
    - 'ereply'
    - 'ac'
    - 'eac'
    - 'amsg'
    - 'eamsg'
    - 'ehelpop'
enforcement:
  strict-ip-checking: true
  priorities:
    bans: 'HIGHEST'
    mutes: 'HIGHEST'
fetchers:
  uuids:
    internal: true
    ashcon: true
    mojang: true
  geoip:
    ipStack:
      enable: false
      key: 'nokey'
    freeGeoIp: true
    ipApi: true
logs:
  log-to-console-threshold: 800
  log-directory-keep-alive: 20
do-not-touch-version: 1