#
#
# # ${project.name}
# # v${project.version}
#
#
#
# The configuration is incredibly simple. There is only 1 option to configure for now.
# This option controls whether ${project.name} should block muted players from editing signs.
options:
  anti-sign: true