lang-file: 'en'
formatting:
  permanent-arguments:
    - 'perm'
    - 'permanent'
    - 'permanently'
  permanent-display: 'Permanently'
  console-display: 'Console'
  dates: 'dd/MM/yyyy kk:mm'
reasons:
  permit-blank: false
  default-reason: 'No reason stated.'
enforcement:
  address-strictness: 'NORMAL'
config-version: 1