# What language file should be used for messages?
# For example, 'en' means LibertyBans will look for a file called 'messages_en.yml'
lang-file: 'en'
formatting:
  # There are 2 ways to make permanent punishments. The first is to not specify a time (/ban <player> <reason>).
  # The second is to specify a permanent amount of time (/ban <player> perm <reason>).
  # When typing commands, what time arguments will be counted as permanent?
  permanent-arguments:
    - 'perm'
    - 'permanent'
    - 'permanently'
  # How should 'permanent' be displayed as a length of time?
  permanent-display: 'Permanently'
  # How should the console be displayed?
  console-display: 'Console'
  # How should dates be formatted? Follows Java's DateTimeFormatter.ofPattern
  dates: 'dd/MM/yyyy kk:mm'
reasons:
  # Are blank reasons permitted?
  # If blank reasons are not permitted, staff must specify the full reason
  # If blank reasons are permitted, the default reason is used
  permit-blank: false
  # If the above is true, what is the default reason to use when staff do not specify a reason?
  default-reason: 'No reason stated.'
enforcement:
  #
  # How strict should IP-based punishments be?
  # Available options are LENIENT, NORMAL, and STRICT
  #
  # LENIENT - If the player's current address matches the punished address, the punishment applies to the player
  # NORMAL - If any of player's past addresses matches the punished address, the punishment applies to the player
  # STRICT - If any of player's past addresses match any related address linked by a common player, the punishment applies to the player
  address-strictness: 'NORMAL'
  #
  # A list of commands muted players will not be able to execute
  #
  # This list supports subcommands, which will be enforced if the executed command starts with the list entry.
  # Additionally, colons in commands, such as"pluginname:cmd", cannot be used to bypass this.
  mute-commands:
    - 'me'
    - 'say'
    - 'msg'
    - 'reply'
    - 'r'
    - 'whisper'
    - 'tell'
# Options relating to finding UUIDs from names, and vice-versa
# LibertyBans will first check its own caches before using these resources.
player-uuid-resolution:
  #
  # What kind of UUIDs do your players have?
  # Available options are ONLINE, OFFLINE, MIXED
  #
  # For most servers this will be 'ONLINE'
  # For offline servers with no premium UUIDs, this should be 'OFFLINE'
  # For offline servers which have some premium UUIDs, this should be 'MIXED'
  #
  server-type: 'ONLINE'
  # If the server is in ONLINE mode, what web APIs should LibertyBans use when it cannot find a UUID itself?
  # Available options are 'MOJANG', 'ASHCON', and 'MCHEADS'. They will be queried sequentially in the order specified.
  # (If the server is not in ONLINE mode, this option is ignored)
  web-api-resolvers:
    - 'ASHCON'
    - 'MCHEADS'
    - 'MOJANG'
# Do not touch this
config-version: 1